/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metier;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
/**
 *
 * @author C103-image
 */
public class fen_gererAssociation extends javax.swing.JFrame {

    /**
     * Creates new form fen_gererAssociation
     */
    public fen_gererAssociation() {
        initComponents();
        afficherTableAssociation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_Association = new javax.swing.JTable();
        btn_close = new javax.swing.JButton();
        btn_AjoutAssoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_Association.setModel(new ModeletableAssociation());
        jScrollPane1.setViewportView(table_Association);

        btn_close.setText("fermer");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_AjoutAssoc.setText("Ajouter une association");
        btn_AjoutAssoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AjoutAssocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_close, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_AjoutAssoc, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AjoutAssoc)
                .addGap(24, 24, 24)
                .addComponent(btn_close)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_AjoutAssocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AjoutAssocActionPerformed
       fen_AjoutAssociation fenetre_AjoutAssociation = new fen_AjoutAssociation();
       fenetre_AjoutAssociation.setVisible(true);
    }//GEN-LAST:event_btn_AjoutAssocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fen_gererAssociation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fen_gererAssociation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fen_gererAssociation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fen_gererAssociation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fen_gererAssociation().setVisible(true);
            }
        });
    }

    public void afficherTableAssociation()
    {
                        Connection conn;
                        Statement stmt;
                        ResultSet rs;
                        String pilote="org.gjt.mm.mysql.Driver";
                        String url = new String("jdbc:mysql://localhost/gymnase");
                        
                        try
                        {
                            Class.forName(pilote);
                            conn = DriverManager.getConnection(url,"root","");
                            stmt = conn.createStatement();
                            rs = stmt.executeQuery("select * from association");
                            int i = 0;
                            while (rs.next())
                            {
                              
                                table_Association.setValueAt(rs.getString("refAsso"),i,0);
                                table_Association.setValueAt(rs.getString("ville"),i,1);
                                table_Association.setValueAt(rs.getString("adresse"),i,2);
                                table_Association.setValueAt(rs.getString("nomResponsable"),i,3);
                                i++;
                               
                            }
                            rs.close();
                            stmt.close();
                            conn.close();
                        }
                        catch (SQLException E)
                        {
                            System.out.println("SQLException" + E.getMessage());
                            System.out.println("SQLState" + E.getSQLState());
                            System.out.println("VendorError" + E.getErrorCode());
                        }
                        catch (ClassNotFoundException E)
                        {
                            E.printStackTrace();
                        }
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AjoutAssoc;
    private javax.swing.JButton btn_close;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Association;
    // End of variables declaration//GEN-END:variables
}
