/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metier;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
/**
 *
 * @author C103-image
 */
public class fen_Admin extends javax.swing.JFrame {

    /**
     * Creates new form fen_Admin
     */
    
    public fen_Admin() {
        initComponents();
        afficherTableAssociation();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed_pane_admin = new javax.swing.JTabbedPane();
        jTabAssos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Association = new javax.swing.JTable();
        buttonAjoutAsso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbed_pane_admin.setName("tabbedPaneAdmin"); // NOI18N

        jTabAssos.setToolTipText("");
        jTabAssos.setName("tabAsso"); // NOI18N

        table_Association.setModel(new ModeletableAssociation());
        jScrollPane1.setViewportView(table_Association);

        buttonAjoutAsso.setText("Ajouter une association");
        buttonAjoutAsso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAjoutAssoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jTabAssosLayout = new javax.swing.GroupLayout(jTabAssos);
        jTabAssos.setLayout(jTabAssosLayout);
        jTabAssosLayout.setHorizontalGroup(
            jTabAssosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTabAssosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTabAssosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTabAssosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAjoutAsso)))
                .addContainerGap())
        );
        jTabAssosLayout.setVerticalGroup(
            jTabAssosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTabAssosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(buttonAjoutAsso)
                .addContainerGap())
        );

        tabbed_pane_admin.addTab("Gérer les associations", jTabAssos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        tabbed_pane_admin.addTab("tab2", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        tabbed_pane_admin.addTab("tab3", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        tabbed_pane_admin.addTab("tab4", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbed_pane_admin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbed_pane_admin))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAjoutAssoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAjoutAssoMouseClicked
        // TODO add your handling code here:
          fen_AjoutAssociation fenetre = new fen_AjoutAssociation();
           fenetre.setVisible(true);
    }//GEN-LAST:event_buttonAjoutAssoMouseClicked

    private void btn_GererAccueilActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       fen_gererAccueillir fenetreGererAccueillir = new fen_gererAccueillir();
       fenetreGererAccueillir.setVisible(true);
    }                                                
  
                                                 
                                                     
    private void btn_fermerActionPerformed(java.awt.event.ActionEvent evt) {                                           
       this.dispose();
    }                                          

                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fen_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fen_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fen_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fen_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fen_Admin().setVisible(true);
                
            }
        });        
      
    }  
   private void afficherTableAssociation()
    {
                        Connection conn;
                        Statement stmt;
                        ResultSet rs;
                        String pilote="org.gjt.mm.mysql.Driver";
                        String url = "jdbc:mysql://localhost/gestiongymnase";
                        
                        try
                        {
                            Class.forName(pilote);
                            conn = DriverManager.getConnection(url,"root","");
                            stmt = conn.createStatement();
                            rs = stmt.executeQuery("select * from association");
                            int i = 0;
                            while (rs.next())
                            {
                              
                                table_Association.setValueAt(rs.getString("refAsso"),i,0);
                                table_Association.setValueAt(rs.getString("ville"),i,1);
                                table_Association.setValueAt(rs.getString("adresse"),i,2);
                                table_Association.setValueAt(rs.getString("nomResponsable"),i,3);
                                i++;
                               
                            }
                            rs.close();
                            stmt.close();
                            conn.close();
                        }
                        catch (SQLException E)
                        {
                            System.out.println("SQLException" + E.getMessage());
                            System.out.println("SQLState" + E.getSQLState());
                            System.out.println("VendorError" + E.getErrorCode());
                        }
                        catch (ClassNotFoundException E)
                        {
                            E.printStackTrace();
                        }
            }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjoutAsso;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jTabAssos;
    private javax.swing.JTabbedPane tabbed_pane_admin;
    private javax.swing.JTable table_Association;
    // End of variables declaration//GEN-END:variables
}
